services:
  - type: web_service
    name: agri-ai-backend
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r ../requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: GROQ_API_KEY
        fromDatabase: false
      - key: ALLOWED_ORIGINS
        fromDatabase: false
      - key: FLASK_DEBUG
        fromDatabase: false
      - key: SECRET_KEY
        fromDatabase: false
