services:
  - type: web_service
    name: agri-ai-backend
    env: python
    plan: free
    region: oregon
    pythonVersion: "3.11.9"
    buildCommand: pip install -r requirements.txt
    startCommand: cd server && python app.py
    envVars:
      - key: GROQ_API_KEY
        fromDatabase: false
      - key: ALLOWED_ORIGINS
        fromDatabase: false
      - key: FLASK_DEBUG
        fromDatabase: false
      - key: SECRET_KEY
        fromDatabase: false
